[phases.install]
cmds = [
  "pip install --no-cache-dir torch --index-url https://download.pytorch.org/whl/cpu",
  "pip install --no-cache-dir -r requirements.txt"
]

[start]
cmd = "python xenone_discord_bot.py"
